---
id: embedding_mruby_into_c_and_an_actual_example
base_name: psvr
tags:
- mruby
- c
- ofpsvr
presentation_date:
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: P.S.V.R
  email: pmq2001@gmail.com
  rubygems_user: pmq20
  slideshare_user: ssuser75e7be
  speaker_deck_user: pmq20
